### PR TITLE
minor changes to admin portal docs

### PR DESCRIPTION
**Pull request by isi-lincoln**

### CODE REVIEW

**Comment by isi-lincoln** [comment]
https://github.com/ceftb/docs/pull/1/commits/6a915cd50beb1b846f61137a61dbfba424c8f612

removes all the content of merge api, I assume that this is because twirl/swirl/swagger, whatever it is that is used to generate the api docs is no longer done through ascii doctor.

**Comment by rcgoodfellow** [comment]
just remove that part from your PR, otherwise looks good

**Comment by isi-lincoln** [comment]
Not a clean way, but i kept the commit and pulled master's version of merge-api's docs

**Comment by isi-lincoln** [comment]
i've hamfisted the commit, going to remove it all, but keep the html which was not committed in previous, one more time...

**Pull request merged**
